// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaSoft.Data.Context;

#nullable disable

namespace PharmaSoft.Data.Migrations
{
    [DbContext(typeof(PharmaContext))]
    [Migration("20260512035851_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmaSoft.Data.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaId")
                        .HasName("PK__Categori__F353C1C5E037566A");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("LimiteCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0.00m);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RncCedula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RNC_Cedula");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClienteId")
                        .HasName("PK__Clientes__71ABD0A7DAC6EF43");

                    b.HasIndex(new[] { "RncCedula" }, "UQ__Clientes__554ADC6A51A518E9")
                        .IsUnique()
                        .HasFilter("[RNC_Cedula] IS NOT NULL");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.Compra", b =>
                {
                    b.Property<int>("CompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompraID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompraId"));

                    b.Property<DateTime?>("FechaCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NumeroFacturaProveedor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int")
                        .HasColumnName("ProveedorID");

                    b.Property<string>("TipoPago")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalCompra")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("CompraId")
                        .HasName("PK__Compras__067DA725CB505B59");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.CuentasPorCobrar", b =>
                {
                    b.Property<int>("CxCid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CxCID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CxCid"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("VentaID");

                    b.HasKey("CxCid")
                        .HasName("PK__CuentasP__1884E33C3B157190");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VentaId");

                    b.ToTable("CuentasPorCobrar");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.CuentasPorPagar", b =>
                {
                    b.Property<int>("CxPid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CxPID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CxPid"));

                    b.Property<int>("CompraId")
                        .HasColumnType("int")
                        .HasColumnName("CompraID");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int")
                        .HasColumnName("ProveedorID");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("CxPid")
                        .HasName("PK__CuentasP__2B8D7CE83D0A6A21");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("CuentasPorPagar");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.DetalleCompra", b =>
                {
                    b.Property<int>("DetalleCompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetalleCompraID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleCompraId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CompraId")
                        .HasColumnType("int")
                        .HasColumnName("CompraID");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("int")
                        .HasColumnName("MedicamentoID");

                    b.Property<decimal>("PrecioCostoUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("DetalleCompraId")
                        .HasName("PK__DetalleC__F7FC189A4B103DD5");

                    b.HasIndex("CompraId");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("DetalleCompras");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.DetalleVenta", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetalleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("LoteId")
                        .HasColumnType("int")
                        .HasColumnName("LoteID");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("VentaID");

                    b.HasKey("DetalleId")
                        .HasName("PK__DetalleV__6E19D6FAEBC23E91");

                    b.HasIndex("LoteId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.LotesInventario", b =>
                {
                    b.Property<int>("LoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LoteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoteId"));

                    b.Property<int>("CantidadActual")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("int")
                        .HasColumnName("MedicamentoID");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LoteId")
                        .HasName("PK__LotesInv__E6EAE6F88F0AB7ED");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("LotesInventario");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.Medicamento", b =>
                {
                    b.Property<int>("MedicamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicamentoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicamentoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("PrincipioActivo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int")
                        .HasColumnName("ProveedorID");

                    b.Property<bool?>("RequiereReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.HasKey("MedicamentoId")
                        .HasName("PK__Medicame__003D65F308DB0ECC");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex(new[] { "CodigoBarras" }, "UQ__Medicame__F61589C8B5D33220")
                        .IsUnique()
                        .HasFilter("[CodigoBarras] IS NOT NULL");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.PagosCliente", b =>
                {
                    b.Property<int>("PagoClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PagoClienteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoClienteId"));

                    b.Property<int>("CxCid")
                        .HasColumnType("int")
                        .HasColumnName("CxCID");

                    b.Property<DateTime?>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("PagoClienteId")
                        .HasName("PK__PagosCli__7A06804746EB57F7");

                    b.HasIndex("CxCid");

                    b.ToTable("PagosClientes");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.PagosProveedore", b =>
                {
                    b.Property<int>("PagoProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PagoProveedorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoProveedorId"));

                    b.Property<int>("CxPid")
                        .HasColumnType("int")
                        .HasColumnName("CxPID");

                    b.Property<DateTime?>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("PagoProveedorId")
                        .HasName("PK__PagosPro__D09663A5632D04E3");

                    b.HasIndex("CxPid");

                    b.ToTable("PagosProveedores");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.Proveedore", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProveedorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProveedorId")
                        .HasName("PK__Proveedo__61266BB9F87D2A0F");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VentaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaId"));

                    b.Property<DateTime?>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("VentaId")
                        .HasName("PK__Ventas__5B41514C6BD66B9A");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.Compra", b =>
                {
                    b.HasOne("PharmaSoft.Data.Models.Proveedore", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("ProveedorId")
                        .IsRequired()
                        .HasConstraintName("FK_Compras_Proveedores");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.CuentasPorCobrar", b =>
                {
                    b.HasOne("PharmaSoft.Data.Models.Cliente", "Cliente")
                        .WithMany("CuentasPorCobrars")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_CxC_Clientes");

                    b.HasOne("PharmaSoft.Data.Models.Venta", "Venta")
                        .WithMany("CuentasPorCobrars")
                        .HasForeignKey("VentaId")
                        .IsRequired()
                        .HasConstraintName("FK_CxC_Ventas");

                    b.Navigation("Cliente");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.CuentasPorPagar", b =>
                {
                    b.HasOne("PharmaSoft.Data.Models.Compra", "Compra")
                        .WithMany("CuentasPorPagars")
                        .HasForeignKey("CompraId")
                        .IsRequired()
                        .HasConstraintName("FK_CxP_Compras");

                    b.HasOne("PharmaSoft.Data.Models.Proveedore", "Proveedor")
                        .WithMany("CuentasPorPagars")
                        .HasForeignKey("ProveedorId")
                        .IsRequired()
                        .HasConstraintName("FK_CxP_Proveedores");

                    b.Navigation("Compra");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.DetalleCompra", b =>
                {
                    b.HasOne("PharmaSoft.Data.Models.Compra", "Compra")
                        .WithMany("DetalleCompras")
                        .HasForeignKey("CompraId")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleC_Compras");

                    b.HasOne("PharmaSoft.Data.Models.Medicamento", "Medicamento")
                        .WithMany("DetalleCompras")
                        .HasForeignKey("MedicamentoId")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleC_Medicamentos");

                    b.Navigation("Compra");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.DetalleVenta", b =>
                {
                    b.HasOne("PharmaSoft.Data.Models.LotesInventario", "Lote")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("LoteId")
                        .IsRequired()
                        .HasConstraintName("FK_Detalle_Lotes");

                    b.HasOne("PharmaSoft.Data.Models.Venta", "Venta")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("VentaId")
                        .IsRequired()
                        .HasConstraintName("FK_Detalle_Ventas");

                    b.Navigation("Lote");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.LotesInventario", b =>
                {
                    b.HasOne("PharmaSoft.Data.Models.Medicamento", "Medicamento")
                        .WithMany("LotesInventarios")
                        .HasForeignKey("MedicamentoId")
                        .IsRequired()
                        .HasConstraintName("FK_Lotes_Medicamentos");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.Medicamento", b =>
                {
                    b.HasOne("PharmaSoft.Data.Models.Categoria", "Categoria")
                        .WithMany("Medicamentos")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK_Medicamentos_Categorias");

                    b.HasOne("PharmaSoft.Data.Models.Proveedore", "Proveedor")
                        .WithMany("Medicamentos")
                        .HasForeignKey("ProveedorId")
                        .IsRequired()
                        .HasConstraintName("FK_Medicamentos_Proveedores");

                    b.Navigation("Categoria");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.PagosCliente", b =>
                {
                    b.HasOne("PharmaSoft.Data.Models.CuentasPorCobrar", "CxC")
                        .WithMany("PagosClientes")
                        .HasForeignKey("CxCid")
                        .IsRequired()
                        .HasConstraintName("FK_Pagos_CxC");

                    b.Navigation("CxC");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.PagosProveedore", b =>
                {
                    b.HasOne("PharmaSoft.Data.Models.CuentasPorPagar", "CxP")
                        .WithMany("PagosProveedores")
                        .HasForeignKey("CxPid")
                        .IsRequired()
                        .HasConstraintName("FK_Pagos_CxP");

                    b.Navigation("CxP");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.Categoria", b =>
                {
                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.Cliente", b =>
                {
                    b.Navigation("CuentasPorCobrars");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.Compra", b =>
                {
                    b.Navigation("CuentasPorPagars");

                    b.Navigation("DetalleCompras");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.CuentasPorCobrar", b =>
                {
                    b.Navigation("PagosClientes");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.CuentasPorPagar", b =>
                {
                    b.Navigation("PagosProveedores");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.LotesInventario", b =>
                {
                    b.Navigation("DetalleVenta");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.Medicamento", b =>
                {
                    b.Navigation("DetalleCompras");

                    b.Navigation("LotesInventarios");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.Proveedore", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("CuentasPorPagars");

                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("PharmaSoft.Data.Models.Venta", b =>
                {
                    b.Navigation("CuentasPorCobrars");

                    b.Navigation("DetalleVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
